package twin

// This file was generated by ChatGPT so I didn't have to. Sweet! I even asked
// it about licensing terms, and it said CC0, so I'll just take it. Even better!

func color256ToRGB(color256 uint8) (r, g, b uint8) {
	if color256 < 16 {
		// Standard ANSI colors
		return standardAnsiColors[color256][0], standardAnsiColors[color256][1], standardAnsiColors[color256][2]
	}

	// Extended 256 colors
	color256 -= 16
	r = (color256 / 36) * 85
	g = ((color256 % 36) / 6) * 85
	b = (color256 % 6) * 85

	return r, g, b
}

// This table modified to match the VGA colors documented here:
// https://en.wikipedia.org/wiki/ANSI_escape_code#3-bit_and_4-bit
var standardAnsiColors = [16][3]uint8{
	{0, 0, 0},       // Black
	{170, 0, 0},     // Red
	{0, 170, 0},     // Green
	{170, 85, 0},    // Yellow
	{0, 0, 170},     // Blue
	{170, 0, 170},   // Magenta
	{0, 170, 170},   // Cyan
	{170, 170, 170}, // White
	{85, 85, 85},    // Bright Black
	{255, 85, 85},   // Bright Red
	{85, 255, 85},   // Bright Green
	{255, 255, 85},  // Bright Yellow
	{85, 85, 255},   // Bright Blue
	{255, 85, 255},  // Bright Magenta
	{85, 255, 255},  // Bright Cyan
	{255, 255, 255}, // Bright White
}
