.TH MOAR 1 2022-07-21
.SH NAME
moar \- the nice pager
.SH SYNOPSIS
.B moar
[options]
.IR file
.br
.B "moar \-\-help"
.br
.B "moar \-\-version"
.SH DESCRIPTION
.B moar
is a pager much like
.I less
(1), but with generally nicer out-of-the-box behavior.
.PP
More information and screenshots: https://github.com/walles/moar#readme
.PP
Inside of \fBmoar\fR, press
.B ?
to access the built-in help.
.PP
Input is expected to be (optionally compressed) UTF-8 text.
Invalid / unprintable characters are by default rendered as '?'.
.SH OPTIONS
Multiple-choice options all have the default value listed first.
.PP
All of these options can be appended to the
.B MOAR
environment variable for persistent configuration.
.PP
Doing
.B moar --help
will also list these options.
.TP
\fB\-\-colors\fR={\fBauto\fR | \fB8\fR | \fB16\fR | \fB256\fR | \fB16M\fR}
Size of color palette we output to the terminal
.TP
\fB\-\-debug\fR
Print debug logs after exiting, less verbose than
.B \-\-trace
.TP
\fB\-\-follow\fR
Scrolls automatically to follow piped input, just like
.B tail \-f
.TP
\fB\-\-lang\fR=string
Used for highlighting.
Without this flag highlighting is based on the input file name.
Valid values are MIME types like \fBtext/x-markdown\fP, file extensions like \fBmd\fP or language names like \fBmarkdown\fP.
For the source of truth on what is supported exactly, look in https://github.com/alecthomas/chroma/tree/master/lexers/embedded or its parent directory.
.TP
\fB\-\-mousemode\fR={\fBauto\fR | \fBselect\fR | \fBscroll\fR}
Guarantee selecting text with the mouse works but maybe not mouse scrolling.
Or guarantee mouse scrolling works but selecting text requiring extra effort.
Details here: https://github.com/walles/moar/blob/master/MOUSE.md
.TP
\fB\-\-no\-clear\-on\-exit\fR
Retain screen contents when exiting moar
.TP
\fB\-\-no\-linenumbers\fR
Hide line numbers on startup, press left arrow key to show
.TP
\fB\-\-no\-statusbar\fR
Hide the status bar, toggle with
.B =
.TP
\fB\-\-quit\-if\-one\-screen\fR
Print input contents without paging if the input fits on one screen
.TP
\fB\-\-render\-unprintable\fR={\fBhighlight\fR | \fBwhitespace\fR}
How unprintable characters are rendered
.TP
\fB\-\-scroll\-left\-hint\fR=string
UTF-8 character indicating the view can scroll left, defaults to an inverse \fB<\fR.
This can be a string containing ANSI formatting.
The word
.B ESC
in caps will be interpreted as one escape character.
Example value for faint (using ANSI SGR code 2) tilde characters:
.B ESC[2m~
.TP
\fB\-\-scroll\-right\-hint\fR=string
UTF-8 character indicating the view can scroll right, defaults to an inverse \fB>\fR.
This can be a string containing ANSI formatting.
The word
.B ESC
in caps will be interpreted as one escape character.
Example value for faint (using ANSI SGR code 2) tilde characters:
.B ESC[2m~
.TP
\fB\-\-shift\fR=int
Arrow keys side scroll amount. Or try ALT+arrow to scroll one column at a time.
.TP
\fB\-\-statusbar\fR={\fBinverse\fR | \fBplain\fR | \fBbold\fR}
Status bar style
.TP
\fB\-\-style\fR={\fBnative\fR | \fIstyle\fR}
Highlighting style from https://xyproto.github.io/splash/docs/longer/all.html
.TP
\fB\-\-trace\fR
Print trace logs after exiting, more verbose than
.B \-\-debug
.TP
\fB\-\-wrap\fR
Wrap long lines, toggle with
.B w
.TP
\fB\+\1234\fR
Immediately scroll to line
.B 1234
.SH ENVIRONMENT
Having
.B PAGER=moar
in your environment will make lots of different programs use
.B moar
as their pager.
.PP
Additional options are read from the
.B MOAR
environment variable if set, just as if those same options had been manually added to each
.B moar
invocation.
.SH BUGS
Kindly report any bugs here: https://github.com/walles/moar/issues
