.TH MOAR 1 2022-07-21
.SH NAME
moar \- the nice pager
.SH SYNOPSIS
.B moar
[options]
.IR file
.br
.B "moar \-\-help"
.SH DESCRIPTION
.B moar
is a pager much like
.I less
(1), but with generally nicer out-of-the-box behavior.
.PP
More information and screenshots: https://github.com/walles/moar#readme
.PP
Inside of
.B moar
, press
.B ?
to access the built-in help.
.SH OPTIONS
.TP
\fB\-\-colors\fR={\fB8\fR | \fB16\fR | \fB256\fR | \fB16M\fR | \fBauto\fR}
Size of color palette we output to the terminal
.TP
\fB\-\-debug\fR
Print debug logs after exiting
.TP
\fB\-\-no\-clear\-on\-exit\fR
Retain screen contents when exiting moar
.TP
\fB\-\-no\-linenumbers\fR
Hide line numbers on startup, press left arrow key to show
.TP
\fB\-\-no\-statusbar\fR
Hide the status bar, toggle with
.B =
.TP
\fB\-\-render\-unprintable\fR={\fBhighlight\fR | \fBwhitespace\fR}
How unprintable characters are rendered
.SH ENVIRONMENT
Additional options are read from the
.B MOAR
environment variable if set, just as if those same options had been manually added to each
.B moar
invocation.
.PP
Having
.B PAGER=moar
in your environment will make lots of different programs use
.B moar
as their pager.
.SH BUGS
Kindly report any bugs here: https://github.com/walles/moar/issues
